services:
  search-bar-backend:
    container_name: search-bar-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - search-bar-redis
      - search-bar-jaeger
      - search-bar-prometheus
    restart: always
    networks:
      - token.network

  search-bar-redis:
    container_name: search-bar-redis
    image: redis:7.0
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
    restart: always
    networks:
      - token.network

  search-bar-jaeger:
    image: jaegertracing/all-in-one:1.37
    container_name: search-bar-jaeger
    ports:
      - '16686:16686' # UI
      - '4318:4318' # OpenTelemetry Collector (OTLP)
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
      COLLECTOR_OTLP_HTTP_PORT: '4318'
    restart: always
    networks:
      - token.network

  search-bar-prometheus:
    image: prom/prometheus:v2.45.0
    container_name: search-bar-prometheus
    ports:
      - '9090:9090' # Prometheus UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    networks:
      - token.network

volumes:
  pgdata:

networks:
  token.network:
    driver: bridge
